language: go
env:
  -  GO111MODULE=on
go:
  - "1.13.x"
os:
  - linux
before_install:
  - go get github.com/mattn/goveralls
script: 
  - sudo -E env "PATH=$PATH" go test -v
  - $GOPATH/bin/goveralls -service=travis-ci
